POST http://localhost:3000/shoppay/add_category
Content-Type: application/json




{
    "name": "fashion",
    "typeImage": []
}


###
POST http://localhost:3000/shoppay/add_subcategory
Content-Type: application/json

{
    "name": "clothing accessories",
    "parent": "5f174e9a8d265f1508cbb7b2"
}


###
POST http://localhost:3000/shoppay/signup
Content-Type: application/json

{
    "password": "pass123"
}


###
POST https://playpesa.herokuapp.com/api/login
Content-Type: application/json

{
    "username": "alimunachipeter@gmail.com",
    "password": "peter123456789"
}


###

GET http://localhost:3000/shoppay
###

GET http://192.168.0.12:3000/shoppay/get_subcategory/5f174e8b8d265f1508cbb7b1


###

GET http://192.168.0.12:3000/shoppay/latest_product
