POST http://localhost:3000/shoppay/add_category
Content-Type: application/json




{
    "name": "fashion",
    "typeImage": []
}


###
POST http://localhost:3000/shoppay/add_subcategory
Content-Type: application/json

{
    "name": "clothing accessories",
    "parent": "5f174e9a8d265f1508cbb7b2"
}


###
POST http://localhost:3000/shoppay/signup
Content-Type: application/json

{
    "password": "pass123"
}


###
POST http://localhost:3000/shoppay/login
Content-Type: application/json

{
    "email": "alimunachipeter@gmail.com"
}


###

GET http://localhost:3000/shoppay
###

GET http://localhost:3000/shoppay/get_subcategory/5f174cd08d265f1508cbb7ac
###

GET http://localhost:3000/shoppay/latest_product
