POST http://localhost:3000/shoppay/add_category
Content-Type: application/json



###
POST http://localhost:3000/shoppay/signup
Content-Type: application/json

{
    "password": "pass123"
}


###
POST http://localhost:3000/shoppay/login
Content-Type: application/json

{
    "email": "alimunachipeter@gmail.com"
}


###

GET http://localhost:3000/shoppay
###

GET http://localhost:3000/shoppay/get_mainCategory
